---

- hosts: all
  become: true
  pre_tasks:

  - name: updates repo cache (Ubuntu)
    tags: always
    apt:
       upgrade: dist
       update_cache: yes
    changed_when: false
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

- hosts: workstations
  become: true
  tasks: 

  - name: install unzip and apps
    package:
      name: unzip

  - name: install other apps on workstation
    apt:
      name: 
       - tmux
       - htop
       - vim-nox
       - tree

  - name: install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.13.1/terraform_0.13.1_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
  
  - name: remove apache2 package
    apt: 
      name: apache2
      state: absent

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for ubuntu servers
    tags: apache, apache2, ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start apache2 service
    tags: apache,apache2,Ubuntu
    service:
     name: apache2
     state: restarted
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS server
    tags: apache, centos, httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy default html site for site
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: mariadb, centos, db
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: mariadb,db,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: remove apache2 package
    apt:
      name: apache2
      state: absent

- hosts: file_servers
  become: true
  tasks:
  
  - name: remove apache2 package
    apt:  
      name: apache2
      state: absent

  - name: install samba package
    tags: samba 
    package:
      name: samba
      state: latest

