---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes 
    when: ansible_distribution == "Ubuntu"

  - name: Install htop tmux vim
    apt: 
      name:
         - htop
         - tmux
         - vim-nox
      state: latest

  - name: remove htop tmux vim
    apt:
      name: 
        - htop
        - tmux
        - vim-nox
      state: absent

