---
- name: Install NFS server and configure exports
  hosts: localhost
  become: true

  tasks:
    - name: Install NFS server
      apt:
        name: nfs-kernel-server
        state: present

    - name: Create /data directory
      file:
        path: /data
        state: directory

    - name: Configure NFS exports
      lineinfile:
        path: /etc/exports
        line: "/data 192.168.56.0/24(rw,sync,no_subtree_check,no_root_squash)"

    - name: Restart NFS server
      service:
        name: nfs-kernel-server
        state: restarted

- name: Install NFS client on worker nodes
  hosts: workers
  become: true

  tasks:
    - name: Install NFS client
      apt:
        name: nfs-common
        state: present