---

- hosts: all
  become: true
  pre_tasks:

  - name: update repoistory index (Ubuntu)
    tags: always
    apt:
      update_cache: yes 
    when: ansible_distribution == "Ubuntu"

  - name: install updates (Centos)
    tags: always
    apt:
      update_cache: yes
      changed_when: false
    when: ansible_distribution == "Centos"

- hosts: all
  become: true
  roles:
    - base

- hosts: workstations
  become: true
  roles:
    - workstations
 
- hosts: web_servers
  tags: apache,apache2,ubuntu
  become: true
  roles:
     - web_servers
 
- hosts: db_servers
  tags: db,mariadb
  become: true
  roles:
     - db_servers
 
- hosts: file_servers
  tags: samba,smb
  become: true
  roles:
     - file_servers
 
