---

- hosts: all
  become: true
  pre_tasks:

  - name: update repoistory index (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install updates (Centos)
    tags: always
    apt:
      update_cache: yes
      changed_when: false
    when: ansible_distribution == "Centos"

 
- hosts: web_servers
  become: true
  tasks:

  - name: install apache2 and php for Ubuntu servers
    tags: apache,apache2,ubuntu
    apt: 
      name: 
        - apache2
        - libapache2-mode-php
      state: latest
    when: ansible_distribution == "ubuntu"

 
- hosts: db_servers
  become: true
  tasks: 

  - name: install mariadb package (ubuntu)
    tags: mariadb,db
    apt: 
      name: mariadb-server
      state: latest
    when: ansible_distribution == "ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

