  - name: start apache2 service
    tags: apache,apache2,Ubuntu
    service:
     name: apache2
     state: restarted
    when: ansible_distribution == "Ubuntu"


  - name: copy file for site
    tags: apache,apache2,httpd
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
