- name: install mariadb server
  tags: db,mariadb,ubuntu
  apt:
     name: mariadb-server
     state: latest
  when: ansible_distribution == "Ubuntu"

- name: install mariadb package (CentOS)
  tags: mariadb, centos, db
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

- name: install mariadb package (Ubuntu)
  tags: mariadb,db,ubuntu
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Ubuntu"
