---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates (Ubuntu)
    tags: always
    apt:
       upgrade: dist
       update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: create Gal  user
    tags: always
    user: 
      name: Gal
      groups: root

  - name: add ssh key for Gal user
    tags: always
    authorized_key:
      user : Gal	
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID9C8V8/px3yYF8ZF5y+pxQ2EaiaphA7HXLN43Dj1fU2 ansible"


  - name: add sudoers files for Gal
    tags: always
    copy:
      src: sudoer_Gal
      dest: /etc/sudoers.d/Gal
      owner: root
      group: root
      mode: 0440



- hosts: workstations
  become: true
  tasks: 

  - name: install unzip
    package:
      name: unzip

  - name: install Terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.13.1/terraform_0.13.1_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for ubuntu servers
    tags: apache, apache2, ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: start apache2 service
    tags: apache,apache2,Ubuntu
    service:
     name: apache2
     state: restarted
    when: ansible_distribution == "Ubuntu"

  - name: install apache and php for CentOS server
    tags: apache, centos, httpd
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: copy default html site for site
    tags: apache,apache2,httpd
    copy: 
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package (CentOS)
    tags: mariadb, centos, db
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"

  - name: install mariadb package (Ubuntu)
    tags: mariadb,db,ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true
  tasks:

  - name: install samba package
    tags: samba 
    package:
      name: samba
      state: latest

