---

- hosts: all
  become: true
  tasks:

  - name: install apache2 and php packages for Ubuntu
    apt:
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
     
  - name: uninstall Tmux
    apt:
      name:
        - tmux
      state: absent
