- name: install unzip
  package:
    name: unzip

- name: install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.13.1/terraform_0.13.1_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: install Tree app.
  apt: 
    name: tree

- name: install htop
  apt:
    name:
      - htop
    state: latest
