- name: install unzip
  package:
    name: unzip

- name: install Terraform
  unarchive:
    src: https://releases.hashicorp.com/terraform/0.13.5/terraform_0.13.5_linux_amd64.zip
    dest: /usr/local/bin
    remote_src: yes
    mode: 0755
    owner: root
    group: root

- name: install Apps on workstation.
  apt:
    name: 
     - tmux
     - htop
     - vim-nox
     - tree
     - tilix
     - net-tools 
  #state: latest
